# Generated by Django 5.2.9 on 2025-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_task_step_actionlog_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16),
        ),
    ]
