# Generated by Django 5.2.9 on 2025-12-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='task_step',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='difficulty_level',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='taskstep',
            old_name='order_index',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_active_date',
            new_name='last_active',
        ),
        migrations.RemoveField(
            model_name='taskstep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='turbo_until',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='mood',
            field=models.IntegerField(choices=[(1, '😔'), (2, '😐'), (3, '🙂'), (4, '😀'), (5, '🤩')], default=3),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivation_mode',
            field=models.CharField(choices=[('soft', 'Soft'), ('balanced', 'Balanced'), ('hardcore', 'Hardcore'), ('reward', 'Reward')], default='balanced', max_length=16),
        ),
    ]
